package io.github.summer.boot.base;

/**
 * 标准错误枚举
 *
 * @author changebooks@qq.com
 */
public enum Errors implements IResult {
    /**
     * 错误码 : 错误信息
     */
    SUCCESS(Code.SUCCESS_NUM, Message.SUCCESS),
    FORBIDDEN(Code.FORBIDDEN, Message.FORBIDDEN),
    PAGE_NOT_FOUND(Code.PAGE_NOT_FOUND, Message.PAGE_NOT_FOUND),
    METHOD_NOT_ALLOWED(Code.METHOD_NOT_ALLOWED, Message.METHOD_NOT_ALLOWED),
    SYSTEM_RUN_ERR(Code.SYSTEM_RUN_ERR, Message.SYSTEM_RUN_ERR),
    SCRIPT_RUN_ERR(Code.SCRIPT_RUN_ERR, Message.SCRIPT_RUN_ERR),
    IDEMPOTENT(Code.IDEMPOTENT, Message.IDEMPOTENT),
    CONFLICT(Code.CONFLICT, Message.CONFLICT),
    ARGS_REQUIRED(Code.ARGS_REQUIRED, Message.ARGS_REQUIRED),
    ARGS_ILLEGAL(Code.ARGS_ILLEGAL, Message.ARGS_ILLEGAL),
    ARGS_ERR(Code.ARGS_ERR, Message.ARGS_ERR),
    RESULT_REQUIRED(Code.RESULT_REQUIRED, Message.RESULT_REQUIRED),
    RESULT_ILLEGAL(Code.RESULT_ILLEGAL, Message.RESULT_ILLEGAL),
    RESULT_ERR(Code.RESULT_ERR, Message.RESULT_ERR),
    JSON_ERR(Code.JSON_ERR, Message.JSON_ERR),
    XML_ERR(Code.XML_ERR, Message.XML_ERR),
    FILE_REQUIRED(Code.FILE_REQUIRED, Message.FILE_REQUIRED),
    FILE_ILLEGAL(Code.FILE_ILLEGAL, Message.FILE_ILLEGAL),
    FILE_ERR(Code.FILE_ERR, Message.FILE_ERR),
    DIRECTORY_REQUIRED(Code.DIRECTORY_REQUIRED, Message.DIRECTORY_REQUIRED),
    DIRECTORY_ILLEGAL(Code.DIRECTORY_ILLEGAL, Message.DIRECTORY_ILLEGAL),
    DIRECTORY_ERR(Code.DIRECTORY_ERR, Message.DIRECTORY_ERR),
    RESOURCE_REQUIRED(Code.RESOURCE_REQUIRED, Message.RESOURCE_REQUIRED),
    RESOURCE_ILLEGAL(Code.RESOURCE_ILLEGAL, Message.RESOURCE_ILLEGAL),
    RESOURCE_ERR(Code.RESOURCE_ERR, Message.RESOURCE_ERR),
    CONSTRAINT_NOT_NULL(Code.CONSTRAINT_NOT_NULL, Message.CONSTRAINT_NOT_NULL),
    CONSTRAINT_UNSIGNED(Code.CONSTRAINT_UNSIGNED, Message.CONSTRAINT_UNSIGNED),
    CONSTRAINT_UNIQUE(Code.CONSTRAINT_UNIQUE, Message.CONSTRAINT_UNIQUE),
    AGGREGATE_ERR(Code.AGGREGATE_ERR, Message.AGGREGATE_ERR),
    FIND_ERR(Code.FIND_ERR, Message.FIND_ERR),
    INSERT_ERR(Code.INSERT_ERR, Message.INSERT_ERR),
    UPDATE_ERR(Code.UPDATE_ERR, Message.UPDATE_ERR),
    DELETE_ERR(Code.DELETE_ERR, Message.DELETE_ERR),
    DB_FIND_ERR(Code.DB_FIND_ERR, Message.DB_FIND_ERR),
    DB_INSERT_ERR(Code.DB_INSERT_ERR, Message.DB_INSERT_ERR),
    DB_UPDATE_ERR(Code.DB_UPDATE_ERR, Message.DB_UPDATE_ERR),
    DB_DELETE_ERR(Code.DB_DELETE_ERR, Message.DB_DELETE_ERR),
    CACHE_FIND_ERR(Code.CACHE_FIND_ERR, Message.CACHE_FIND_ERR),
    CACHE_INSERT_ERR(Code.CACHE_INSERT_ERR, Message.CACHE_INSERT_ERR),
    CACHE_UPDATE_ERR(Code.CACHE_UPDATE_ERR, Message.CACHE_UPDATE_ERR),
    CACHE_DELETE_ERR(Code.CACHE_DELETE_ERR, Message.CACHE_DELETE_ERR),
    ATTRIBUTE_FIND_ERR(Code.ATTRIBUTE_FIND_ERR, Message.ATTRIBUTE_FIND_ERR),
    ATTRIBUTE_INSERT_ERR(Code.ATTRIBUTE_INSERT_ERR, Message.ATTRIBUTE_INSERT_ERR),
    ATTRIBUTE_UPDATE_ERR(Code.ATTRIBUTE_UPDATE_ERR, Message.ATTRIBUTE_UPDATE_ERR),
    ATTRIBUTE_DELETE_ERR(Code.ATTRIBUTE_DELETE_ERR, Message.ATTRIBUTE_DELETE_ERR),
    FILE_READ_ERR(Code.FILE_READ_ERR, Message.FILE_READ_ERR),
    FILE_CREATE_ERR(Code.FILE_CREATE_ERR, Message.FILE_CREATE_ERR),
    FILE_WRITE_ERR(Code.FILE_WRITE_ERR, Message.FILE_WRITE_ERR),
    FILE_DELETE_ERR(Code.FILE_DELETE_ERR, Message.FILE_DELETE_ERR),
    DIRECTORY_READ_ERR(Code.DIRECTORY_READ_ERR, Message.DIRECTORY_READ_ERR),
    DIRECTORY_CREATE_ERR(Code.DIRECTORY_CREATE_ERR, Message.DIRECTORY_CREATE_ERR),
    DIRECTORY_MODIFY_ERR(Code.DIRECTORY_MODIFY_ERR, Message.DIRECTORY_MODIFY_ERR),
    DIRECTORY_DELETE_ERR(Code.DIRECTORY_DELETE_ERR, Message.DIRECTORY_DELETE_ERR),
    UPLOAD_ERR(Code.UPLOAD_ERR, Message.UPLOAD_ERR),
    DOWNLOAD_ERR(Code.DOWNLOAD_ERR, Message.DOWNLOAD_ERR),
    HTTP_ERR(Code.HTTP_ERR, Message.HTTP_ERR),
    RPC_ERR(Code.RPC_ERR, Message.RPC_ERR),
    SEND_MSG_ERR(Code.SEND_MSG_ERR, Message.SEND_MSG_ERR),
    TOKEN_REQUIRED(Code.TOKEN_REQUIRED, Message.TOKEN_REQUIRED),
    TOKEN_ILLEGAL(Code.TOKEN_ILLEGAL, Message.TOKEN_ILLEGAL),
    TOKEN_ERR(Code.TOKEN_ERR, Message.TOKEN_ERR),
    TOKEN_POSITIVE(Code.TOKEN_POSITIVE, Message.TOKEN_POSITIVE),
    TOKEN_NON_NEGATIVE(Code.TOKEN_NON_NEGATIVE, Message.TOKEN_NON_NEGATIVE),
    TOKEN_UNSUPPORTED(Code.TOKEN_UNSUPPORTED, Message.TOKEN_UNSUPPORTED),
    TOKEN_CONFLICT(Code.TOKEN_CONFLICT, Message.TOKEN_CONFLICT),
    TOKEN_EXPIRED(Code.TOKEN_EXPIRED, Message.TOKEN_EXPIRED),
    UNKNOWN_ERR(Code.UNKNOWN_ERR, Message.UNKNOWN_ERR),
    TIME_REQUIRED(Code.TIME_REQUIRED, Message.TIME_REQUIRED),
    TIME_ILLEGAL(Code.TIME_ILLEGAL, Message.TIME_ILLEGAL),
    TIME_ERR(Code.TIME_ERR, Message.TIME_ERR),
    DATE_REQUIRED(Code.DATE_REQUIRED, Message.DATE_REQUIRED),
    DATE_ILLEGAL(Code.DATE_ILLEGAL, Message.DATE_ILLEGAL),
    DATE_ERR(Code.DATE_ERR, Message.DATE_ERR),
    SORT_REQUIRED(Code.SORT_REQUIRED, Message.SORT_REQUIRED),
    SORT_ILLEGAL(Code.SORT_ILLEGAL, Message.SORT_ILLEGAL),
    SORT_ERR(Code.SORT_ERR, Message.SORT_ERR),
    SORT_POSITIVE(Code.SORT_POSITIVE, Message.SORT_POSITIVE),
    SORT_NON_NEGATIVE(Code.SORT_NON_NEGATIVE, Message.SORT_NON_NEGATIVE),
    PROGRESS_REQUIRED(Code.PROGRESS_REQUIRED, Message.PROGRESS_REQUIRED),
    PROGRESS_ILLEGAL(Code.PROGRESS_ILLEGAL, Message.PROGRESS_ILLEGAL),
    PROGRESS_ERR(Code.PROGRESS_ERR, Message.PROGRESS_ERR),
    PROGRESS_POSITIVE(Code.PROGRESS_POSITIVE, Message.PROGRESS_POSITIVE),
    PROGRESS_NON_NEGATIVE(Code.PROGRESS_NON_NEGATIVE, Message.PROGRESS_NON_NEGATIVE),
    VERSION_REQUIRED(Code.VERSION_REQUIRED, Message.VERSION_REQUIRED),
    VERSION_ILLEGAL(Code.VERSION_ILLEGAL, Message.VERSION_ILLEGAL),
    VERSION_ERR(Code.VERSION_ERR, Message.VERSION_ERR),
    VERSION_POSITIVE(Code.VERSION_POSITIVE, Message.VERSION_POSITIVE),
    VERSION_NON_NEGATIVE(Code.VERSION_NON_NEGATIVE, Message.VERSION_NON_NEGATIVE),
    VERSION_UNSUPPORTED(Code.VERSION_UNSUPPORTED, Message.VERSION_UNSUPPORTED),
    TYPE_REQUIRED(Code.TYPE_REQUIRED, Message.TYPE_REQUIRED),
    TYPE_ILLEGAL(Code.TYPE_ILLEGAL, Message.TYPE_ILLEGAL),
    TYPE_ERR(Code.TYPE_ERR, Message.TYPE_ERR),
    TYPE_POSITIVE(Code.TYPE_POSITIVE, Message.TYPE_POSITIVE),
    TYPE_NON_NEGATIVE(Code.TYPE_NON_NEGATIVE, Message.TYPE_NON_NEGATIVE),
    TYPE_UNSUPPORTED(Code.TYPE_UNSUPPORTED, Message.TYPE_UNSUPPORTED),
    JDBC_TYPE_REQUIRED(Code.JDBC_TYPE_REQUIRED, Message.JDBC_TYPE_REQUIRED),
    JDBC_TYPE_ILLEGAL(Code.JDBC_TYPE_ILLEGAL, Message.JDBC_TYPE_ILLEGAL),
    JDBC_TYPE_ERR(Code.JDBC_TYPE_ERR, Message.JDBC_TYPE_ERR),
    JDBC_TYPE_POSITIVE(Code.JDBC_TYPE_POSITIVE, Message.JDBC_TYPE_POSITIVE),
    JDBC_TYPE_NON_NEGATIVE(Code.JDBC_TYPE_NON_NEGATIVE, Message.JDBC_TYPE_NON_NEGATIVE),
    JDBC_TYPE_UNSUPPORTED(Code.JDBC_TYPE_UNSUPPORTED, Message.JDBC_TYPE_UNSUPPORTED),
    JAVA_TYPE_REQUIRED(Code.JAVA_TYPE_REQUIRED, Message.JAVA_TYPE_REQUIRED),
    JAVA_TYPE_ILLEGAL(Code.JAVA_TYPE_ILLEGAL, Message.JAVA_TYPE_ILLEGAL),
    JAVA_TYPE_ERR(Code.JAVA_TYPE_ERR, Message.JAVA_TYPE_ERR),
    JAVA_TYPE_POSITIVE(Code.JAVA_TYPE_POSITIVE, Message.JAVA_TYPE_POSITIVE),
    JAVA_TYPE_NON_NEGATIVE(Code.JAVA_TYPE_NON_NEGATIVE, Message.JAVA_TYPE_NON_NEGATIVE),
    JAVA_TYPE_UNSUPPORTED(Code.JAVA_TYPE_UNSUPPORTED, Message.JAVA_TYPE_UNSUPPORTED),
    ID_REQUIRED(Code.ID_REQUIRED, Message.ID_REQUIRED),
    ID_ILLEGAL(Code.ID_ILLEGAL, Message.ID_ILLEGAL),
    ID_ERR(Code.ID_ERR, Message.ID_ERR),
    ID_POSITIVE(Code.ID_POSITIVE, Message.ID_POSITIVE),
    ID_NON_NEGATIVE(Code.ID_NON_NEGATIVE, Message.ID_NON_NEGATIVE),
    ID_UNSUPPORTED(Code.ID_UNSUPPORTED, Message.ID_UNSUPPORTED),
    ID_CONFLICT(Code.ID_CONFLICT, Message.ID_CONFLICT),
    TABLE_ID_REQUIRED(Code.TABLE_ID_REQUIRED, Message.TABLE_ID_REQUIRED),
    TABLE_ID_ILLEGAL(Code.TABLE_ID_ILLEGAL, Message.TABLE_ID_ILLEGAL),
    TABLE_ID_ERR(Code.TABLE_ID_ERR, Message.TABLE_ID_ERR),
    TABLE_ID_POSITIVE(Code.TABLE_ID_POSITIVE, Message.TABLE_ID_POSITIVE),
    TABLE_ID_NON_NEGATIVE(Code.TABLE_ID_NON_NEGATIVE, Message.TABLE_ID_NON_NEGATIVE),
    TABLE_ID_UNSUPPORTED(Code.TABLE_ID_UNSUPPORTED, Message.TABLE_ID_UNSUPPORTED),
    TABLE_ID_CONFLICT(Code.TABLE_ID_CONFLICT, Message.TABLE_ID_CONFLICT),
    ATTRIBUTE_ID_REQUIRED(Code.ATTRIBUTE_ID_REQUIRED, Message.ATTRIBUTE_ID_REQUIRED),
    ATTRIBUTE_ID_ILLEGAL(Code.ATTRIBUTE_ID_ILLEGAL, Message.ATTRIBUTE_ID_ILLEGAL),
    ATTRIBUTE_ID_ERR(Code.ATTRIBUTE_ID_ERR, Message.ATTRIBUTE_ID_ERR),
    ATTRIBUTE_ID_POSITIVE(Code.ATTRIBUTE_ID_POSITIVE, Message.ATTRIBUTE_ID_POSITIVE),
    ATTRIBUTE_ID_NON_NEGATIVE(Code.ATTRIBUTE_ID_NON_NEGATIVE, Message.ATTRIBUTE_ID_NON_NEGATIVE),
    ATTRIBUTE_ID_UNSUPPORTED(Code.ATTRIBUTE_ID_UNSUPPORTED, Message.ATTRIBUTE_ID_UNSUPPORTED),
    ATTRIBUTE_ID_CONFLICT(Code.ATTRIBUTE_ID_CONFLICT, Message.ATTRIBUTE_ID_CONFLICT),
    BIZ_ID_REQUIRED(Code.BIZ_ID_REQUIRED, Message.BIZ_ID_REQUIRED),
    BIZ_ID_ILLEGAL(Code.BIZ_ID_ILLEGAL, Message.BIZ_ID_ILLEGAL),
    BIZ_ID_ERR(Code.BIZ_ID_ERR, Message.BIZ_ID_ERR),
    BIZ_ID_POSITIVE(Code.BIZ_ID_POSITIVE, Message.BIZ_ID_POSITIVE),
    BIZ_ID_NON_NEGATIVE(Code.BIZ_ID_NON_NEGATIVE, Message.BIZ_ID_NON_NEGATIVE),
    BIZ_ID_UNSUPPORTED(Code.BIZ_ID_UNSUPPORTED, Message.BIZ_ID_UNSUPPORTED),
    BIZ_ID_CONFLICT(Code.BIZ_ID_CONFLICT, Message.BIZ_ID_CONFLICT),
    FLOW_ID_REQUIRED(Code.FLOW_ID_REQUIRED, Message.FLOW_ID_REQUIRED),
    FLOW_ID_ILLEGAL(Code.FLOW_ID_ILLEGAL, Message.FLOW_ID_ILLEGAL),
    FLOW_ID_ERR(Code.FLOW_ID_ERR, Message.FLOW_ID_ERR),
    FLOW_ID_POSITIVE(Code.FLOW_ID_POSITIVE, Message.FLOW_ID_POSITIVE),
    FLOW_ID_NON_NEGATIVE(Code.FLOW_ID_NON_NEGATIVE, Message.FLOW_ID_NON_NEGATIVE),
    FLOW_ID_UNSUPPORTED(Code.FLOW_ID_UNSUPPORTED, Message.FLOW_ID_UNSUPPORTED),
    FLOW_ID_CONFLICT(Code.FLOW_ID_CONFLICT, Message.FLOW_ID_CONFLICT),
    USER_ID_REQUIRED(Code.USER_ID_REQUIRED, Message.USER_ID_REQUIRED),
    USER_ID_ILLEGAL(Code.USER_ID_ILLEGAL, Message.USER_ID_ILLEGAL),
    USER_ID_ERR(Code.USER_ID_ERR, Message.USER_ID_ERR),
    USER_ID_POSITIVE(Code.USER_ID_POSITIVE, Message.USER_ID_POSITIVE),
    USER_ID_NON_NEGATIVE(Code.USER_ID_NON_NEGATIVE, Message.USER_ID_NON_NEGATIVE),
    USER_ID_UNSUPPORTED(Code.USER_ID_UNSUPPORTED, Message.USER_ID_UNSUPPORTED),
    USER_ID_CONFLICT(Code.USER_ID_CONFLICT, Message.USER_ID_CONFLICT),
    PLATFORM_ID_REQUIRED(Code.PLATFORM_ID_REQUIRED, Message.PLATFORM_ID_REQUIRED),
    PLATFORM_ID_ILLEGAL(Code.PLATFORM_ID_ILLEGAL, Message.PLATFORM_ID_ILLEGAL),
    PLATFORM_ID_ERR(Code.PLATFORM_ID_ERR, Message.PLATFORM_ID_ERR),
    PLATFORM_ID_POSITIVE(Code.PLATFORM_ID_POSITIVE, Message.PLATFORM_ID_POSITIVE),
    PLATFORM_ID_NON_NEGATIVE(Code.PLATFORM_ID_NON_NEGATIVE, Message.PLATFORM_ID_NON_NEGATIVE),
    PLATFORM_ID_UNSUPPORTED(Code.PLATFORM_ID_UNSUPPORTED, Message.PLATFORM_ID_UNSUPPORTED),
    PLATFORM_ID_CONFLICT(Code.PLATFORM_ID_CONFLICT, Message.PLATFORM_ID_CONFLICT),
    SHOP_ID_REQUIRED(Code.SHOP_ID_REQUIRED, Message.SHOP_ID_REQUIRED),
    SHOP_ID_ILLEGAL(Code.SHOP_ID_ILLEGAL, Message.SHOP_ID_ILLEGAL),
    SHOP_ID_ERR(Code.SHOP_ID_ERR, Message.SHOP_ID_ERR),
    SHOP_ID_POSITIVE(Code.SHOP_ID_POSITIVE, Message.SHOP_ID_POSITIVE),
    SHOP_ID_NON_NEGATIVE(Code.SHOP_ID_NON_NEGATIVE, Message.SHOP_ID_NON_NEGATIVE),
    SHOP_ID_UNSUPPORTED(Code.SHOP_ID_UNSUPPORTED, Message.SHOP_ID_UNSUPPORTED),
    SHOP_ID_CONFLICT(Code.SHOP_ID_CONFLICT, Message.SHOP_ID_CONFLICT),

    ;

    /**
     * 错误码
     * 0-正确、gt 0-错误、lt 0-弃用
     */
    private final int code;

    /**
     * 错误信息
     * ok-正确、!ok-错误
     */
    private final String message;

    Errors(int code, String message) {
        this.code = code;
        this.message = message;
    }

    @Override
    public int getCode() {
        return code;
    }

    @Override
    public String getMessage() {
        return message;
    }

}
